import Head from "next/head";
import "../styles/global.css";
function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Pokemon - Group I</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
